[package]
name = "metaconfig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version="0.11"}
proc-macro2 = { version="1.0"}
quote = { version="1.0" }
syn = { version="1.0" }